import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Serif } from "next/font/google";
import "./globals.css";
import "lenis/dist/lenis.css";
import { SmoothScroll } from "./components/SmoothScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
});

const TITLE = "Hueclid";
const DESCRIPTION =
  "Turn any image into an accessible color palette. Hueclid reads the colors that make up a photo or screenshot and turns them into a ranked, weighted palette built for real UI use, not just five swatches that happen to look fine alone.";
const SITE_URL = "https://hueclid.cinexg.com";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: SITE_URL,
    siteName: TITLE,
    type: "website",
    images: [{ url: "/og-banner.png", width: 1200, height: 630, alt: "Hueclid" }],
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    images: ["/og-banner.png"],
  },
};

// Runs before hydration so the right theme is set on first paint, no
// flash of the wrong mode. Light is the default: this only ever adds
// the "dark" class, and only when the visitor previously chose it.
const THEME_INIT_SCRIPT = `
(function () {
  try {
    if ("scrollRestoration" in history) {
      history.scrollRestoration = "manual";
    }
    if (localStorage.getItem("hueclid-theme") === "dark") {
      document.documentElement.classList.add("dark");
    }
  } catch (e) {}
})();
`;

// Static film grain, generated by the browser from an SVG filter so
// it costs no network request. It sits above everything at a very
// low opacity and takes no pointer events, its only job is to stop
// the large flat color fields from looking like dead pixels.
const GRAIN =
  "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='200'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='200' height='200' filter='url(%23n)'/%3E%3C/svg%3E\")";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      /* THEME_INIT_SCRIPT adds the "dark" class to this element
         before React hydrates, so the class list it finds will not
         match the one the server sent. That difference is the whole
         point of the script, this tells React to leave it alone
         rather than warn about it. */
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${instrumentSerif.variable} h-full antialiased`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
      </head>
      <body className="relative min-h-full flex flex-col">
        <div
          aria-hidden
          className="pointer-events-none fixed inset-0 z-[70] opacity-[var(--grain-opacity)] mix-blend-overlay"
          style={{ backgroundImage: GRAIN }}
        />
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
